//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration_And_Login_Desktop_Application_Assecment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admain
    {
        public Nullable<int> admin_ID { get; set; }
        public string admin_username_ { get; set; }
        public string admin_pass { get; set; }
    }
}
