//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration_And_Login_Desktop_Application_Assecment
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public int Phone_Number { get; set; }
        public string City { get; set; }
    }
}
